@startuml "BUC3"
left to right direction

actor/ "Usuario" <<Business Actor>> as Usuario
actor/ "Administrador" <<Business Worker>> as Admin

usecase/ "Impartir Educacion Financiera" as BUC3

Usuario --> BUC3
Admin --> BUC3

skinparam usecase {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam actor {
  BackgroundColor #C7F4FF
  BorderColor #7A1631
}
skinparam Arrow {
  Color #7A1631
}
@enduml