@startuml
title SUC01 - Gestionar Flujo de Caja y Billeteras Multi-moneda

|Usuario|

start

:Crear una billetera;
:Definir el nombre de la cuenta;
:Seleccionar la divisa;

:Registrar un ingreso o un gasto;
:Indicar el monto;

if (¿Desea clasificar el movimiento?) then (Sí)
:Asignar una categoría;
endif

if (¿Desea corregir un movimiento?) then (Sí)
:Modificar o eliminar la transacción;
endif

:Revisar el balance de sus billeteras;

stop

@enduml