@startuml
title SUC03 - Impartir Educación Financiera Gamificada

|Administrador|

start

:Gestionar contenido educativo;
:Publicar nuevas lecciones;
:Organizar el temario;

|Usuario|

:Seleccionar curso;
:Estudiar el contenido;
:Resolver evaluación temática;

if (¿Aprueba la evaluación?) then (Sí)

:Recibir insignia de logro;
:Continuar con el siguiente módulo;

stop

else (No)

:Repasar el contenido del módulo;
:Resolver nuevamente la evaluación;

stop

endif

@enduml