@startuml
title SUC04 - Evaluar Hábitos Financieros

|Usuario|

start

:Responder cuestionario de hábitos financieros;

if (¿Cuestionario completo?) then (Sí)

:Entregar cuestionario;

|Administrador|

:Evaluar respuestas;
:Determinar nivel de consciencia financiera;
:Analizar los resultados generales de los usuarios;

stop

else (No)

:Completar las preguntas pendientes;

stop

endif

@enduml