@startuml
title SUC05 - Generar Recomendaciones Personalizadas

start

if (¿Existen transacciones en la última semana?) then (Sí)

    :Generar reporte semanal;
    :Mostrar estadísticas;
    :Generar recomendaciones automáticas;
    stop

else (No)

    :Mostrar pantalla vacía;
    :Mostrar mensaje:
    "Aún no tienes movimientos registrados
    esta semana para generar analíticas";
    stop

endif

@enduml